name: Docker Images CI
on:
  push:
    branches: [ "main" ]
jobs:
  push-backend:
    runs-on: ubuntu-latest
    environment: docker-images-ci-actions-env
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build ./backend -t "${{ vars.DOCKERHUB_USERNAME }}/school-dining-room-menu-backend:latest"
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}
      - name: Push to Docker Hub
        run: docker push "${{ vars.DOCKERHUB_USERNAME }}/school-dining-room-menu-backend:latest"
  push-frontend:
    runs-on: ubuntu-latest
    environment: docker-images-ci-actions-env
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build ./frontend -t "${{ vars.DOCKERHUB_USERNAME }}/school-dining-room-menu-frontend:latest"
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}
      - name: Push to Docker Hub
        run: docker push "${{ vars.DOCKERHUB_USERNAME }}/school-dining-room-menu-frontend:latest"
  push-docs:
    runs-on: ubuntu-latest
    environment: docker-images-ci-actions-env
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build ./docs -t "${{ vars.DOCKERHUB_USERNAME }}/school-dining-room-menu-docs:latest"
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}
      - name: Push to Docker Hub
        run: docker push "${{ vars.DOCKERHUB_USERNAME }}/school-dining-room-menu-docs:latest"
